DROP DATABASE IF EXISTS `thought`;

CREATE DATABASE `thought` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE 'mysql';

GRANT ALL PRIVILEGES ON thought.* TO 'thought'@'127.0.0.1' IDENTIFIED BY 'thought' WITH GRANT OPTION;

FLUSH PRIVILEGES;
